#!/bin/sh

# Copyright (c) 2014 Simon Deziel <simon.deziel@gmail.com>

# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Explicitly set the PATH to that of ENV_SUPATH in /etc/login.defs and unset
# various other variables. For details, see:
# https://wiki.ubuntu.com/SecurityTeam/AppArmorPolicyReview#Execute_rules
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export ENV=
export CDPATH=

SCRIPT_NAME="$(basename $0)"

p_error () {
  echo "Error: $1" >&2
  exit 1
}

long_usage () {
  cat << EOF
Copyright (c) 2014 Simon Deziel

Report the names of the processes using deleted libraries

Usage:
  $SCRIPT_NAME
EOF
  exit 0
}

# Check arguments
[ "$#" -ne 0 ] && long_usage

# Check if /proc/*/maps are readable by testing with PID=1
cat /proc/1/maps >/dev/null 2>&1 || p_error "Unable to read /proc/1/maps, are you running $SCRIPT_NAME with root privileges?"

GREP_RE='[[:space:]]((/.+)?/(lib|bin/)[^/]+ \(deleted\)|\(deleted\)(/.+)?/(lib|bin/)[^/]+)$'
SED_RE='s#^/proc/\([0-9]\+\)/maps:.*#\1#'

# Check if we can use a fast path (/proc/$pid/comm available and no prelink)
if [ -e "/proc/1/comm" -a ! -x "$(which prelink)" ]; then # fast path
  for pid in $(grep -m1 -HE "$GREP_RE" /proc/[0-9]*/maps 2>/dev/null | sed "$SED_RE"); do
    cat /proc/$pid/comm 2>/dev/null
  done | sort -u
else # slow path
  for pid in $(grep -HE "$GREP_RE" /proc/[0-9]*/maps 2>/dev/null | sed "/\.#prelink#\./d; $SED_RE"); do
    sed -n "/^Name:[[:space:]]\+/ s/^Name:[[:space:]]\+//p;q" /proc/$pid/status 2>/dev/null
  done | sort -u
fi
