#!/bin/sh

# Report the names of QEMU VMs needing to be restart at the hypervisor level.
# Copyright (C) 2015-2017 Simon Deziel <simon@sdeziel.info>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Explicitly set the PATH to that of ENV_SUPATH in /etc/login.defs and unset
# various other variables. For details, see:
# https://wiki.ubuntu.com/SecurityTeam/AppArmorPolicyReview#Execute_rules
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export ENV=
export CDPATH=

SCRIPT_NAME="$(basename "$0")"

p_error () {
  echo "Error: $1" >&2
  exit 1
}

usage () {
  cat << EOF
Copyright (C) 2015-2017 Simon Deziel

Report the names of QEMU VMs needing to be restart at the hypervisor level.

Usage:
  $SCRIPT_NAME
EOF
  exit 0
}

# Check arguments
[ "$#" -ne 0 ] && usage

# Check if /proc/*/maps are readable by testing with PID=1
cat "/proc/1/maps" >/dev/null 2>&1 || p_error "Unable to read /proc/1/maps, are you running $SCRIPT_NAME with root privileges?"

SED_RE='s/^\([0-9]\+\).\+ -name \([^ ]\+\).*/\1 \2/'
GREP_RE='[[:space:]]((/.+)?/(lib|s?bin/)[^/]+ \(deleted\)|\(deleted\)(/.+)?/(lib|s?bin/)[^/]+)$'

pgrep -a ^qemu-system-.+ | sed "$SED_RE" | while read -r pid vmname; do
  grep -q -m1 -E "$GREP_RE" "/proc/$pid/maps" 2>/dev/null && echo "$vmname"
done | paste -s -d " "
